using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace proyecto_termotasajero.Models
{
    public class ParametrosOperacionPrecipitador
    {
        public int ID { get; set; }
        public DateTime FechaHoraInicio { get; set; }
        public DateTime FechaHoraFinalizacion { get; set; }
        public string? Email { get; set; }
        public string? NombreOperador { get; set; }
        public string? OperadorTurno { get; set; }
        public string? IPF14 { get; set; }
        public string? IPF13 { get; set; }
        public string? IPF15 { get; set; }
        public string? IPF16 { get; set; }
        public string? IPF12 { get; set; }
        public string? IPF11 { get; set; }
        public string? IPF10 { get; set; }
        public string? IPF9 { get; set; }
        public string? IPF5 { get; set; }
        public string? IPF6 { get; set; }
        public string? IPF7 { get; set; }
        public string? IPF8 { get; set; }
        public string? IPF4 { get; set; }
        public string? IPF3 { get; set; }
        public string? IPF2 { get; set; }
        public string? IPF1 { get; set; }
        public decimal Temp1B2 { get; set; }
        public string? Nivel1B2 { get; set; }
        public decimal Temp2B2 { get; set; }
        public string? Nivel2B2 { get; set; }
        public decimal Temp3B2 { get; set; }
        public string? Nivel3B2 { get; set; }
        public decimal Temp4B2 { get; set; }
        public string? Nivel4B2 { get; set; }
        public decimal Temp4B1 { get; set; }
        public string? Nivel4B1 { get; set; }
        public decimal Temp3B1 { get; set; }
        public string? Nivel3B1 { get; set; }
        public decimal Temp2B1 { get; set; }
        public string? Nivel2B1 { get; set; }
        public decimal Temp1B1 { get; set; }
        public string? Nivel1B1 { get; set; }
        public decimal Temp1A2 { get; set; }
        public string? Nivel1A2 { get; set; }
        public decimal Temp2A2 { get; set; }
        public string? Nivel2A2 { get; set; }
        public decimal Temp3A2 { get; set; }
        public string? Nivel3A2 { get; set; }
        public decimal Temp4A2 { get; set; }
        public string? Nivel4A2 { get; set; }
        public decimal Temp4A1 { get; set; }
        public string? Nivel4A1 { get; set; }
        public decimal Temp3A1 { get; set; }
        public string? Nivel3A1 { get; set; }
        public decimal Temp2A1 { get; set; }
        public string? Nivel2A1 { get; set; }
        public decimal Temp1A1 { get; set; }
        public string? Nivel1A1 { get; set; }
        public decimal Campo1A1_Amps { get; set; }
        public decimal Campo1A1_Volts { get; set; }
        public decimal Campo1A1_mA { get; set; }
        public decimal Campo1A1_KV { get; set; }
        public string? Campo1A1_SPM { get; set; }
        public decimal Campo1A1_KW { get; set; }
        public decimal Campo1A1_Deg { get; set; }
        public decimal Campo1A2_Amps { get; set; }
        public decimal Campo1A2_Volts { get; set; }
        public decimal Campo1A2_mA { get; set; }
        public decimal Campo1A2_KV { get; set; }
        public string? Campo1A2_SPM { get; set; }
        public decimal Campo1A2_KW { get; set; }
        public decimal Campo1A2_Deg { get; set; }
        public decimal Campo1B1_Amps { get; set; }
        public decimal Campo1B1_Volts { get; set; }
        public decimal Campo1B1_mA { get; set; }
        public decimal Campo1B1_KV { get; set; }
        public string? Campo1B1_SPM { get; set; }
        public decimal Campo1B1_KW { get; set; }
        public decimal Campo1B1_Deg { get; set; }
        public decimal Campo1B2_Amps { get; set; }
        public decimal Campo1B2_Volts { get; set; }
        public decimal Campo1B2_mA { get; set; }
        public decimal Campo1B2_KV { get; set; }
        public string? Campo1B2_SPM { get; set; }
        public decimal Campo1B2_KW { get; set; }
        public decimal Campo1B2_Deg { get; set; }
        public decimal Campo2A1_Amps { get; set; }
        public decimal Campo2A1_Volts { get; set; }
        public decimal Campo2A1_mA { get; set; }
        public decimal Campo2A1_KV { get; set; }
        public string? Campo2A1_SPM { get; set; }
        public decimal Campo2A1_KW { get; set; }
        public decimal Campo2A1_Deg { get; set; }
        public decimal Campo2B2_Amps { get; set; }
        public decimal Campo2B2_Volts { get; set; }
        public decimal Campo2B2_mA { get; set; }
        public decimal Campo2B2_KV { get; set; }
        public string? Campo2B2_SPM { get; set; }
        public decimal Campo2B2_KW { get; set; }
        public decimal Campo2B2_Deg { get; set; }
        public decimal Campo2B1_Amps { get; set; }
        public decimal Campo2B1_Volts { get; set; }
        public decimal Campo2B1_mA { get; set; }
        public decimal Campo2B1_KV { get; set; }
        public string? Campo2B1_SPM { get; set; }
        public decimal Campo2B1_KW { get; set; }
        public decimal Campo2B1_Deg { get; set; }
        public decimal Campo2A2_Amps { get; set; }
        public decimal Campo2A2_Volts { get; set; }
        public decimal Campo2A2_mA { get; set; }
        public decimal Campo2A2_KV { get; set; }
        public string? Campo2A2_SPM { get; set; }
        public decimal Campo2A2_KW { get; set; }
        public decimal Campo2A2_Deg { get; set; }
        public decimal Campo3A1_Amps { get; set; }
        public decimal Campo3A1_Volts { get; set; }
        public decimal Campo3A1_mA { get; set; }
        public decimal Campo3A1_KV { get; set; }
        public string? Campo3A1_SCR { get; set; }
        public decimal Campo3A1_KW { get; set; }
        public string? Campo3A1_SM { get; set; }
        public decimal Campo3A2_Amps { get; set; }
        public decimal Campo3A2_Volts { get; set; }
        public decimal Campo3A2_mA { get; set; }
        public decimal Campo3A2_KV { get; set; }
        public string? Campo3A2_SCR { get; set; }
        public decimal Campo3A2_KW { get; set; }
        public string? Campo3A2_SM { get; set; }
        public decimal Campo4A1_Amps { get; set; }
        public decimal Campo4A1_Volts { get; set; }
        public decimal Campo4A1_mA { get; set; }
        public decimal Campo4A1_KV { get; set; }
        public string? Campo4A1_SCR { get; set; }
        public decimal Campo4A1_KW { get; set; }
        public string? Campo4A1_SM { get; set; }
        public decimal Campo4A2_Amps { get; set; }
        public decimal Campo4A2_Volts { get; set; }
        public decimal Campo4A2_mA { get; set; }
        public decimal Campo4A2_KV { get; set; }
        public string? Campo4A2_SCR { get; set; }
        public decimal Campo4A2_KW { get; set; }
        public string? Campo4A2_SM { get; set; }
        public decimal Campo3B1_Amps { get; set; }
        public decimal Campo3B1_Volts { get; set; }
        public decimal Campo3B1_mA { get; set; }
        public decimal Campo3B1_KV { get; set; }
        public string? Campo3B1_SCR { get; set; }
        public decimal Campo3B1_KW { get; set; }
        public string? Campo3B1_SM { get; set; }
        public decimal Campo3B2_Amps { get; set; }
        public decimal Campo3B2_Volts { get; set; }
        public decimal Campo3B2_mA { get; set; }
        public decimal Campo3B2_KV { get; set; }
        public string? Campo3B2_SCR { get; set; }
        public decimal Campo3B2_KW { get; set; }
        public string? Campo3B2_SM { get; set; }
        public decimal Campo4B1_Amps { get; set; }
        public decimal Campo4B1_Volts { get; set; }
        public decimal Campo4B1_mA { get; set; }
        public decimal Campo4B1_KV { get; set; }
        public string? Campo4B1_SCR { get; set; }
        public decimal Campo4B1_KW { get; set; }
        public string? Campo4B1_SM { get; set; }
        public decimal Campo4B2_Amps { get; set; }
        public decimal Campo4B2_Volts { get; set; }
        public decimal Campo4B2_mA { get; set; }
        public decimal Campo4B2_KV { get; set; }
        public string? Campo4B2_SCR { get; set; }
        public decimal Campo4B2_KW { get; set; }
        public string? Campo4B2_SM { get; set; }
        public string? Observaciones { get; set; }
        public DateTime FechaCreacion { get; set; }
        public string? UsuarioCreacion { get; set; }
    }
}