using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace proyecto_termotasajero.Models
{
    public class ParametrosOperacionTurboGeneracion
    {
        public int ID { get; set; }
        public DateTime FechaHoraInicio { get; set; }
        public DateTime FechaHoraFinalizacion { get; set; }
        public string? CorreoElectronico { get; set; }
        public string? NombreOperador { get; set; }
        public string? OperadorTurno { get; set; }
        public string? EnfriadorAguaAguaA { get; set; }
        public string? EnfriadorAguaAguaB { get; set; }
        public string? BombaReforzadoraA { get; set; }
        public string? BombaReforzadoraB { get; set; }
        public decimal TempEntradaCircuitoCerrado { get; set; }
        public decimal TempSalidaCircuitoAbierto { get; set; }
        public decimal PresionDescargaReforzadoraA { get; set; }
        public decimal PresionDescargaReforzadoraB { get; set; }
        public decimal DeltaPFiltroBombasReforzadoras { get; set; }
        public string? BbaSelloLadoH2 { get; set; }
        public string? BbaSelloLadoAire { get; set; }
        public string? BbaSelloEmergencia { get; set; }
        public string? BbaSelloFlotante { get; set; }
        public string? ExtractorTanqueBucle { get; set; }
        public decimal PresionRefuerzo { get; set; }
        public decimal PresionAceiteLadoH2 { get; set; }
        public decimal PresionAceiteLadoAire { get; set; }
        public decimal TemperaturaAceiteLadoH2 { get; set; }
        public decimal TemperaturaAceiteLadoAire { get; set; }
        public string? EstadoSecadorH2 { get; set; }
        public decimal DewPointEntrada { get; set; }
        public decimal DewPointSalida { get; set; }
        public decimal VlaControlNivelCalentadorBP1CV221 { get; set; }
        public string? BbaVacioA { get; set; }
        public string? BbaVacioB { get; set; }
        public decimal PresionSuccionBbaVacioA { get; set; }
        public decimal PresionAguaSelloBbaVacioB { get; set; }
        public string? EnfriadorA { get; set; }
        public string? EnfriadorB { get; set; }
        public decimal TemperaturaSalidaAgua { get; set; }
        public decimal AperturaValvulaControl { get; set; }
        public string? ExtraccionA { get; set; }
        public string? ExtraccionB { get; set; }
        public decimal PresionSuccionExtraccionAireA { get; set; }
        public decimal PresionSuccionExtraccionAireB { get; set; }
        public string? PurificadorAceite { get; set; }
        public decimal PresionTkAceiteTurbina { get; set; }
        public decimal NivelTkAceiteTurbina { get; set; }
        public string? CargadorA220Vdc { get; set; }
        public string? CargadorB220Vdc { get; set; }
        public string? CargadorA125Vdc { get; set; }
        public string? CargadorB125Vdc { get; set; }
        public string? CargadorA24Vdc { get; set; }
        public string? CargadorB24Vdc { get; set; }
        public decimal CorrienteCargador220ES { get; set; }
        public decimal CorrienteCargador124ES { get; set; }
        public decimal CorrienteCargador24ES { get; set; }
        public string? BAAC_Estado { get; set; }
        public decimal BAAC_TempRetornoAceiteRodamientoLadoInterior { get; set; }
        public decimal BAAC_TempRetornoAceiteRodamientoLadoExterior { get; set; }
        public decimal BAAC_TempAguaSelloLadoInterior { get; set; }
        public decimal BAAC_TempAguaSelloLadoExterior { get; set; }
        public decimal BAAC_PresionAceiteRodamientoLadoInterior { get; set; }
        public decimal BAAC_PresionAceiteRodamientoLadoExterior { get; set; }
        public decimal BAAC_PresionEntradaAguaSello { get; set; }
        public decimal BAAC_PresionDiferencialFiltroAguaSello { get; set; }
        public decimal BAAC_PresionDiferencialFiltroSuccion { get; set; }
        public decimal BAAC_AperturaAguaSelloLadoInterior { get; set; }
        public decimal BAAC_AperturaAguaSelloLadoExterior { get; set; }
        public decimal AcopleBAAC_TempMetalRadial1 { get; set; }
        public decimal AcopleBAAC_TempMetalRadial2 { get; set; }
        public decimal AcopleBAAC_TempMetalRadial3 { get; set; }
        public decimal AcopleBAAC_TempMetalRadial4 { get; set; }
        public decimal AcopleBAAC_TempMetalRadial5 { get; set; }
        public decimal AcopleBAAC_TempMetalRadial6 { get; set; }
        public decimal AcopleBAAC_TempAceiteTrabajoEntradaEnfriador { get; set; }
        public decimal AcopleBAAC_PresionAceiteLubricacion { get; set; }
        public decimal AcopleBAAC_PresionDiferencialFiltroAceite { get; set; }
        public decimal AcopleBAAC_TempAceiteLubricacionEntradaEnfriador { get; set; }
        public decimal AcopleBAAC_TempAceiteLubricacionSalidaEnfriador { get; set; }
        public decimal AcopleBAAC_TempAceiteTrabajoSalidaEnfriador { get; set; }
        public string? BAAB_Estado { get; set; }
        public decimal BAAB_TempRetornoAceiteRodamientoLadoInterior { get; set; }
        public decimal BAAB_TempRetornoAceiteRodamientoLadoExterior { get; set; }
        public decimal BAAB_TempAguaSelloLadoInterior { get; set; }
        public decimal BAAB_TempAguaSelloLadoExterior { get; set; }
        public decimal BAAB_PresionAceiteRodamientoLadoInterior { get; set; }
        public decimal BAAB_PresionAceiteRodamientoLadoExterior { get; set; }
        public decimal BAAB_PresionEntradaAguaSello { get; set; }
        public decimal BAAB_PresionDiferencialFiltroAguaSello { get; set; }
        public decimal BAAB_PresionDiferencialFiltroSuccion { get; set; }
        public decimal BAAB_AperturaAguaSelloLadoInterior { get; set; }
        public decimal BAAB_AperturaAguaSelloLadoExterior { get; set; }
        public decimal AcopleBAAB_TempMetalRadial1 { get; set; }
        public decimal AcopleBAAB_TempMetalRadial2 { get; set; }
        public decimal AcopleBAAB_TempMetalRadial3 { get; set; }
        public decimal AcopleBAAB_TempMetalRadial4 { get; set; }
        public decimal AcopleBAAB_TempMetalRadial5 { get; set; }
        public decimal AcopleBAAB_TempMetalRadial6 { get; set; }
        public decimal AcopleBAAB_TempAceiteTrabajoEntradaEnfriador { get; set; }
        public decimal AcopleBAAB_PresionAceiteLubricacion { get; set; }
        public decimal AcopleBAAB_PresionDiferencialFiltroAceite { get; set; }
        public decimal AcopleBAAB_TempAceiteLubricacionEntradaEnfriador { get; set; }
        public decimal AcopleBAAB_TempAceiteLubricacionSalidaEnfriador { get; set; }
        public decimal AcopleBAAB_TempAceiteTrabajoSalidaEnfriador { get; set; }
        public string? BAAA_Estado { get; set; }
        public decimal BAAA_TempRetornoAceiteRodamientoLadoInterior { get; set; }
        public decimal BAAA_TempRetornoAceiteRodamientoLadoExterior { get; set; }
        public decimal BAAA_TempAguaSelloLadoInterior { get; set; }
        public decimal BAAA_TempAguaSelloLadoExterior { get; set; }
        public decimal BAAA_PresionAceiteRodamientoLadoInterior { get; set; }
        public decimal BAAA_PresionAceiteRodamientoLadoExterior { get; set; }
        public decimal BAAA_PresionEntradaAguaSello { get; set; }
        public decimal BAAA_PresionDiferencialFiltroAguaSello { get; set; }
        public decimal BAAA_PresionDiferencialFiltroSuccion { get; set; }
        public decimal BAAA_AperturaAguaSelloLadoInterior { get; set; }
        public decimal BAAA_AperturaAguaSelloLadoExterior { get; set; }
        public decimal AcopleBAAA_TempMetalRadial1 { get; set; }
        public decimal AcopleBAAA_TempMetalRadial2 { get; set; }
        public decimal AcopleBAAA_TempMetalRadial3 { get; set; }
        public decimal AcopleBAAA_TempMetalRadial4 { get; set; }
        public decimal AcopleBAAA_TempMetalRadial5 { get; set; }
        public decimal AcopleBAAA_TempMetalRadial6 { get; set; }
        public decimal AcopleBAAA_TempAceiteTrabajoEntradaEnfriador { get; set; }
        public decimal AcopleBAAA_PresionAceiteLubricacion { get; set; }
        public decimal AcopleBAAA_PresionDiferencialFiltroAceite { get; set; }
        public decimal AcopleBAAA_TempAceiteLubricacionEntradaEnfriador { get; set; }
        public decimal AcopleBAAA_TempAceiteLubricacionSalidaEnfriador { get; set; }
        public decimal AcopleBAAA_TempAceiteTrabajoSalidaEnfriador { get; set; }
        public string? SecadorAireA { get; set; }
        public string? SecadorAireB { get; set; }
        public decimal TempDewPointSecadorA { get; set; }
        public decimal TempDewPointSecadorB { get; set; }
        public string? CompresorC_Estado { get; set; }
        public decimal CompresorC_TempT1Descarga { get; set; }
        public decimal CompresorC_TempT2LadoSeco { get; set; }
        public decimal CompresorC_PresionP1Carter { get; set; }
        public decimal CompresorC_PresionP2Linea { get; set; }
        public decimal CompresorC_PresionP4Aceite { get; set; }
        public decimal CompresorC_PresionDP1Separador { get; set; }
        public decimal CompresorC_PresionDP2FiltroAceite { get; set; }
        public decimal CompresorC_PresionDP3Aceite { get; set; }
        public string? CompresorA_Estado { get; set; }
        public decimal CompresorA_PresionDescargaConjunto { get; set; }
        public decimal CompresorA_TempDescargaConjunto { get; set; }
        public decimal CompresorA_TempDescargaFase1 { get; set; }
        public decimal CompresorA_PresionEntradaFase2 { get; set; }
        public decimal CompresorA_TempEntradaFase2 { get; set; }
        public decimal CompresorA_PresionDescargaFase2 { get; set; }
        public decimal CompresorA_TempDescargaFase2 { get; set; }
        public decimal CompresorA_TempAceiteRodamientos { get; set; }
        public decimal CompresorA_PresionAceiteRodamientos { get; set; }
        public decimal CompresorA_VacioEntrada { get; set; }
        public decimal CompresorA_CaidaPresionFiltroAceite { get; set; }
        public string? CompresorB_Estado { get; set; }
        public decimal CompresorB_TempDescargaUnidad { get; set; }
        public decimal CompresorB_Temp1aFase { get; set; }
        public decimal CompresorB_PresionAdmision2aFase { get; set; }
        public decimal CompresorB_TempAdmision2aFase { get; set; }
        public decimal CompresorB_PresionDescarga2aFase { get; set; }
        public decimal CompresorB_TempDescarga2aFase { get; set; }
        public decimal CompresorB_PresionAceiteCojinetes { get; set; }
        public decimal CompresorB_TempAceiteCojinetes { get; set; }
        public decimal CompresorB_VacioEntrada { get; set; }
        public string? CompresorB_EstadoFiltroEntrada { get; set; }
        public decimal CompresorB_CaidaPresionFiltroAceite { get; set; }
        public decimal VlaControlNivelCalentadorBP2CV223 { get; set; }
        public decimal CorrienteCompresorB { get; set; }
        public decimal CorrienteCompresorC { get; set; }
        public decimal CorrienteCompresorA { get; set; }
        public decimal VlaControlNivelCalentadorBP3CV224 { get; set; }
        public decimal PI255_PresionAceiteAltaPresion { get; set; }
        public decimal PI257_PresionAceiteDescargaBombaPrincipal { get; set; }
        public decimal PI329_PresionSelloExtremoTurbina { get; set; }
        public decimal PI328_PresionSelloExtremoGenerador { get; set; }
        public string? ExtractorTkBucle { get; set; }
        public decimal PresionSuccionExtractorTkBucle { get; set; }
        public decimal PI230_PresionVaporSelloBP { get; set; }
        public decimal PI238_PresionVaporSalidaCamaraIntermedia { get; set; }
        public decimal VlaControlNivelCalentadorAP5CV226 { get; set; }
        public decimal VlaControlNivelCalentadorAP6CV227 { get; set; }
        public string? Observaciones { get; set; }
        public string? BombaFosfatoDomoA { get; set; }
        public string? BombaFosfatoDomoB { get; set; }
        public string? BombaHidracinaCicloA { get; set; }
        public string? BombaHidracinaCicloB { get; set; }
        public string? BombaHidracinaCtoCerradoA { get; set; }
        public string? BombaHidracinaCtoCerradoB { get; set; }
    }
}